# This is a basic workflow to help you get started with Actions

name: file list diff

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "diff"
  diff:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: List the repo contents
        run: mkdir -p ${{ runner.temp	}}/current && find ${{ github.workspace }} >> ${{ runner.temp	}}/current/file_list
      
      - name: Fetch the file list from the last successful workflow
        # TODO smarter error handling
        continue-on-error: true
        uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          workflow_conclusion: success
          # Optional, will use the branch
          branch: main
          # Optional, defaults to all types
          event: push
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          path: ${{ runner.temp	}}/previous
        
      - name: Upload the new repo file list to an artifact
        uses: actions/upload-artifact@v3
        with:
          name: file-list
          path: ${{ runner.temp	}}/current/file_list

      # this comes last so that the upload will still happen if this fails
      - name: Compare file lists
        run: diff -q ${{ runner.temp }}/previous/ ${{ runner.temp}}/current/
        